apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-serviceaccount
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::119836602066:role/otel-s3-cpe-chi-testotel

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:

  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: otel-serviceaccount
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      terminationGracePeriodSeconds: 60
      initContainers:
        - name: bucket-data
          command: ['aws' , '']
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: 119836602066.dkr.ecr.us-west-2.amazonaws.com/amazon-aws-cli:latest    
      containers:
      - name: myapp
        image: 691504454456.dkr.ecr.us-west-2.amazonaws.com/cpe/tomcat:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        
        
        
        
        
        
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::119836602066:oidc-provider/oidc.eks.us-west-2.amazonaws.com/id/2ECB21BD1BC11FB0A6921FD14A821D84"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-west-2.amazonaws.com/id/2ECB21BD1BC11FB0A6921FD14A821D84:aud": "sts.amazonaws.com",
                    "oidc.eks.us-west-2.amazonaws.com/id/2ECB21BD1BC11FB0A6921FD14A821D84:sub": "system:serviceaccount:cpe-chi-demo:hw-tomcat-iam"
                }
            }
        }
    ]
}        
